version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into amazon ECR
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION
      - REPOSITORY_URI=161452358598.dkr.ecr.us-east-1.amazonaws.com/tweetapp-springboot
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo creating jar of project
      - mvn clean install
      - echo docker Build starting on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file
      - printf '[{"name":"tweet-auth-app","imageUri":"%S"}]' $REPOSITORY_URI:IMAGE_TAG > imagedefinition.json
      - cat imagedefinition.json
artifacts:
  files:
    - imagedefinition.json
    - target/tweet-auth-app.jar
